export const PHISH_SCENARIOS = [
  {
    type: "INCOMING EMAIL",
    sender: "it-support@lsu-helpdesk.com",
    time: "08:42",
    title: "Your account needs verification",
    body: "Your LSU account will be suspended today. Verify your credentials immediately to restore access.",
    link: "lsu-verify-access.com/secure",
    isReal: false,
    clues: [
      "The message mentions your account",
      "The sender domain is not an official LSU domain",
      "The email has a short subject line",
    ],
    correctClue: 1,
  },
  {
    type: "INCOMING DM",
    sender: "@campus_rewards",
    time: "14:17",
    title: "You won free merch",
    body: "Claim your exclusive student reward before midnight. Send your login code so we can confirm your identity.",
    link: "bit.ly/lsu-free-stuff",
    isReal: false,
    clues: [
      "The message mentions a reward",
      "It asks for a login code",
      "The account has a fun username",
    ],
    correctClue: 1,
  },
  {
    type: "INCOMING EMAIL",
    sender: "events@lsu.edu",
    time: "19:03",
    title: "Your event registration is confirmed",
    body: "Your registration for the LSU Cyber Summit is confirmed. View event details and your ticket in the student events portal.",
    link: "events.lsu.edu/cyber-summit",
    isReal: true,
    clues: [
      "The message mentions an event",
      "The link matches the LSU events domain",
      "The email includes a confirmation",
    ],
    correctClue: 1,
  },
  {
    type: "INCOMING TEXT",
    sender: "+1 (225) 555-0184",
    time: "07:11",
    title: "Package delivery failed",
    body: "We could not deliver your package. Confirm your address and pay the small redelivery fee to reschedule.",
    link: "usps-redelivery.help/track",
    isReal: false,
    clues: [
      "It asks for a payment",
      "The message mentions a package",
      "It arrived as a text message",
    ],
    correctClue: 0,
  },
  {
    type: "INCOMING PASSWORD ALERT",
    sender: "accounts@lsu.edu",
    time: "11:26",
    title: "Password changed successfully",
    body: "Your LSU password was changed. If you made this change, no action is needed. If not, contact the ITS Service Desk through myLSU.",
    link: "my.lsu.edu/its-help",
    isReal: true,
    clues: [
      "It does not ask for your password",
      "The message reports a password change",
      "It mentions the ITS Service Desk",
    ],
    correctClue: 0,
  },
  {
    type: "INCOMING SHARED DOC",
    sender: "Jordan Lee via CloudFiles",
    time: "12:54",
    title: "Shared with you: spring budget",
    body: "Jordan Lee shared a document with you. Sign in to review the latest edits and leave comments.",
    link: "cloudfiles-login.net/document/884",
    isReal: false,
    clues: [
      "The service domain is unfamiliar",
      "The message mentions a shared document",
      "It asks you to review edits",
    ],
    correctClue: 0,
  },
  {
    type: "INCOMING MFA REQUEST",
    sender: "Microsoft account team",
    time: "16:32",
    title: "Approve sign-in request",
    body: "We detected a sign-in from a new device. Approve this request only if you started a login within the last few minutes.",
    link: "account.microsoft.com/security",
    isReal: true,
    clues: [
      "It tells you not to approve an unexpected request",
      "The message mentions a new device",
      "It asks about a sign-in",
    ],
    correctClue: 0,
  },
  {
    type: "INCOMING QR POSTER",
    sender: "LSU_EVENT_TEAM",
    time: "18:05",
    title: "Free concert entry",
    body: "Scan to unlock your free ticket. The offer expires when the doors open.",
    link: "QR // destination hidden",
    isReal: false,
    clues: [
      "The destination cannot be previewed",
      "The poster offers concert entry",
      "It is displayed on a poster",
    ],
    correctClue: 0,
  },
  {
    type: "INCOMING INVOICE",
    sender: "billing@campus-print.lsu.edu",
    time: "09:38",
    title: "Invoice ready for review",
    body: "Your requested print order invoice is ready. Review the amount and purchase order in the vendor portal.",
    link: "campus-print.lsu.edu/invoices/2048",
    isReal: true,
    clues: [
      "The domain matches the known vendor",
      "The message contains an invoice",
      "It references a print order",
    ],
    correctClue: 0,
  },
  {
    type: "INCOMING ACCOUNT NOTICE",
    sender: "security@lsu-support.org",
    time: "22:16",
    title: "Final notice: mailbox removal",
    body: "Your mailbox will be permanently removed in 30 minutes. Reply with your password to keep your account active.",
    link: "lsu-support.org/restore",
    isReal: false,
    clues: [
      "It requests your password by reply",
      "The message mentions your mailbox",
      "It uses an account notice subject",
    ],
    correctClue: 0,
  },
];
